/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    parents: ParentAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    parents: Parent;
    students: Student;
    'student-levels': StudentLevel;
    enrollments: Enrollment;
    levels: Level;
    classes: Class;
    coaches: Coach;
    locations: Location;
    attendance: Attendance;
    'class-sessions': ClassSession;
    'session-student-plans': SessionStudentPlan;
    'curriculum-templates': CurriculumTemplate;
    holidays: Holiday;
    'progress-reports': ProgressReport;
    payments: Payment;
    'tuition-cycles': TuitionCycle;
    'tuition-packages': TuitionPackage;
    'expense-categories': ExpenseCategory;
    expenses: Expense;
    refunds: Refund;
    books: Book;
    'book-issues': BookIssue;
    'featured-books': FeaturedBook;
    posts: Post;
    events: Event;
    media: Media;
    'web-locations': WebLocation;
    'web-coaches': WebCoach;
    'web-programs': WebProgram;
    'renewal-requests': RenewalRequest;
    'import-logs': ImportLog;
    users: User;
    'audit-logs': AuditLog;
    'otp-codes': OtpCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    parents: ParentsSelect<false> | ParentsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    'student-levels': StudentLevelsSelect<false> | StudentLevelsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    levels: LevelsSelect<false> | LevelsSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    attendance: AttendanceSelect<false> | AttendanceSelect<true>;
    'class-sessions': ClassSessionsSelect<false> | ClassSessionsSelect<true>;
    'session-student-plans': SessionStudentPlansSelect<false> | SessionStudentPlansSelect<true>;
    'curriculum-templates': CurriculumTemplatesSelect<false> | CurriculumTemplatesSelect<true>;
    holidays: HolidaysSelect<false> | HolidaysSelect<true>;
    'progress-reports': ProgressReportsSelect<false> | ProgressReportsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'tuition-cycles': TuitionCyclesSelect<false> | TuitionCyclesSelect<true>;
    'tuition-packages': TuitionPackagesSelect<false> | TuitionPackagesSelect<true>;
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    'book-issues': BookIssuesSelect<false> | BookIssuesSelect<true>;
    'featured-books': FeaturedBooksSelect<false> | FeaturedBooksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'web-locations': WebLocationsSelect<false> | WebLocationsSelect<true>;
    'web-coaches': WebCoachesSelect<false> | WebCoachesSelect<true>;
    'web-programs': WebProgramsSelect<false> | WebProgramsSelect<true>;
    'renewal-requests': RenewalRequestsSelect<false> | RenewalRequestsSelect<true>;
    'import-logs': ImportLogsSelect<false> | ImportLogsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'otp-codes': OtpCodesSelect<false> | OtpCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Parent | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ParentAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  fullName: string;
  phone: string;
  email?: string | null;
  childAge?: string | null;
  interestedLocation?: (number | null) | Location;
  /**
   * Lớp phụ huynh đăng ký học thử (từ website).
   */
  interestedClass?: (number | null) | Class;
  source: 'google' | 'facebook' | 'gioi_thieu' | 'khac';
  note?: string | null;
  /**
   * Giai đoạn trong pipeline chăm sóc lead. "Đã chốt" được đặt tự động khi chuyển đổi lead thành Phụ huynh + Học viên.
   */
  status: 'moi' | 'da_lien_he' | 'dang_ky_hoc_thu' | 'da_chot' | 'khong_phu_hop';
  /**
   * Nhân viên chăm sóc lead này.
   */
  assignedTo?: (number | null) | User;
  /**
   * Mốc cần liên hệ lại lần tới.
   */
  nextFollowUpAt?: string | null;
  /**
   * Lịch sử tương tác với lead (cuộc gọi, ghi chú, đổi giai đoạn, chuyển đổi…). Entry "Chuyển đổi" được ghi tự động bởi action convertLead.
   */
  activityLog?:
    | {
        type: 'lien_he' | 'ghi_chu' | 'doi_giai_doan' | 'hen_lich' | 'chuyen_doi' | 'khac';
        at?: string | null;
        note?: string | null;
        by?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Thời điểm lead được chuyển thành Phụ huynh + Học viên.
   */
  convertedAt?: string | null;
  /**
   * Bản ghi Phụ huynh sinh ra từ lead này (chống tạo trùng).
   */
  convertedParent?: (number | null) | Parent;
  /**
   * Bản ghi Học viên sinh ra từ lead này.
   */
  convertedStudent?: (number | null) | Student;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * Mã cơ sở giảng dạy (KL/VP, 2–3 ký tự HOA) — dùng để sinh mã lớp. Bỏ trống nếu cơ sở không mở lớp.
   */
  code?: string | null;
  name: string;
  address: string;
  lat?: number | null;
  lng?: number | null;
  /**
   * Dùng thay cho tọa độ lat/lng nếu cần nhúng Google Maps.
   */
  mapEmbedUrl?: string | null;
  phone?: string | null;
  isHeadquarters?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  title: string;
  /**
   * Chọn 1+ cấp độ. Bỏ trống sẽ tự suy từ Tuyến đã chọn.
   */
  level?: ('tot' | 'ma' | 'tuong' | 'xe' | 'hau' | 'vua')[] | null;
  /**
   * Chọn 1+ tuyến. Bỏ trống sẽ tự suy từ Cấp độ đã chọn.
   */
  track?: ('nhap_mon' | 'co_ban' | 'nang_cao')[] | null;
  /**
   * Có thể chọn cả hai để dùng chung một lớp cho nhiều lứa tuổi.
   */
  ageGroup: ('mam_non_4_6' | 'cap_1_cap_2')[];
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location: number | Location;
  coach?: (number | null) | Coach;
  troGiang?: (number | null) | Coach;
  /**
   * Tự động đếm số học viên đang học (Ghi danh có "Đang học"). Không lưu, không nhập tay.
   */
  siSoHienTai?: number | null;
  /**
   * Để trống nếu không giới hạn.
   */
  siSoToiDa?: number | null;
  trangThai?: ('dang_mo' | 'tam_dung' | 'da_dong') | null;
  /**
   * Các buổi cố định hằng tuần.
   */
  lichHoc?:
    | {
        thu: 't2' | 't3' | 't4' | 't5' | 't6' | 't7' | 'cn';
        gioBatDau: string;
        gioKetThuc: string;
        phong?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  /**
   * Khóa định danh để import khớp dòng (idempotent). Không trùng.
   */
  tenTat: string;
  /**
   * Các cách viết tắt khác của GV, ngăn cách bởi dấu phẩy (vd "P.Anh, Panh, Phanh"). Import khớp cả bí danh để gom đúng một người.
   */
  tenTatAlias?: string | null;
  hoTen?: string | null;
  vaiTro?: ('gv' | 'tro_giang' | 'tap_su') | null;
  /**
   * Lưu dạng text để giữ số 0 đầu, không dùng number.
   */
  sdt?: string | null;
  email?: string | null;
  elo?: number | null;
  trangThai?: ('dang_day' | 'nghi') | null;
  /**
   * Tên hiển thị trên website. Import sẽ tự điền từ Họ tên nếu để trống khi tạo mới.
   */
  name: string;
  photo?: (number | null) | Media;
  titles?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Số nhỏ hơn hiển thị trước.
   */
  order?: number | null;
  /**
   * Đơn giá/buổi đứng lớp — dùng tính bảng lương. 🔒 Chỉ tài chính xem.
   */
  luongMoiBuoi?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Một nhân viên có thể có NHIỀU vai trò (quyền là HỢP của các vai trò). Quyết định phạm vi truy cập. Mặc định "Lễ tân" (quyền thấp nhất).
   */
  role: ('admin' | 'manager' | 'coach' | 'accountant' | 'receptionist' | 'assistant')[];
  /**
   * Cơ sở của nhân viên (có thể NHIỀU). Vai trò bị-khóa-theo-cơ-sở (coach, receptionist, assistant) CHỈ đọc/sửa Học viên + Lớp thuộc các cơ sở này. Vai trò global (admin, manager, accountant) xem mọi cơ sở nên không cần gán. BỎ TRỐNG ở vai trò bị-khóa ⇒ không thấy dữ liệu nào (fail-closed).
   */
  location?: (number | Location)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Tài khoản phụ huynh đăng nhập cổng /cong-phu-huynh bằng SĐT + OTP. Khác hoàn toàn với Users (nhân viên CMS).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parents".
 */
export interface Parent {
  id: number;
  fullName: string;
  /**
   * Định danh đăng nhập. Lưu dạng chuẩn hóa, không khoảng trắng/dấu.
   */
  phone: string;
  email?: string | null;
  /**
   * Dùng khi tích hợp Zalo OA ở giai đoạn sau.
   */
  zaloId?: string | null;
  /**
   * Học viên mà phụ huynh này theo dõi. Đồng bộ với Students.parents khi gán.
   */
  children?: (number | Student)[] | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'parents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  fullName: string;
  /**
   * Biệt danh hoặc ghi chú nhận diện từ sổ gốc (cột "nick"): tuổi, tên phụ huynh, quan hệ anh/em… Không hiển thị cho phụ huynh.
   */
  nickname?: string | null;
  dob?: string | null;
  /**
   * Cấp độ hiện tại của học viên (quan hệ tới Levels). Lịch sử qua cấp lưu ở StudentLevels.
   */
  capChinh?: (number | null) | Level;
  location?: (number | null) | Location;
  /**
   * Quan hệ nhiều–nhiều với Parents.children (nhân viên gán từ phía phụ huynh hoặc học viên).
   */
  parents?: (number | Parent)[] | null;
  enrollmentStatus: 'dang_hoc' | 'tam_nghi' | 'da_nghi';
  /**
   * Chỉ nhân viên xem, không hiển thị cho phụ huynh.
   */
  note?: string | null;
  /**
   * Số buổi còn tồn TÍNH ĐẾN HẾT "Ngày chốt số dư". Điền cùng "Ngày chốt số dư" để màn Số buổi tồn lấy đây làm mốc thay vì lần nộp gần nhất.
   */
  soBuoiTonDauKy?: number | null;
  /**
   * Mốc chốt "Số buổi tồn đầu kỳ". Sau ngày này, tồn = số dư đầu + buổi đã nộp − buổi đã học.
   */
  ngayChotSoDu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels".
 */
export interface Level {
  id: number;
  tenTat: string;
  tenDayDu?: string | null;
  thuTu?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-levels".
 */
export interface StudentLevel {
  id: number;
  student: number | Student;
  level: number | Level;
  trangThai?: ('dang_hoc' | 'da_hoan_thanh') | null;
  ngayBatDau?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  class: number | Class;
  ngayBatDau?: string | null;
  ngayKetThuc?: string | null;
  dangHoc?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance".
 */
export interface Attendance {
  id: number;
  student: number | Student;
  date: string;
  status: 'co_mat' | 'vang' | 'phep';
  note?: string | null;
  /**
   * Mã buổi/khối học (vd B1_2025, C44). Thành phần khóa chống trùng.
   */
  buoi?: string | null;
  /**
   * Khớp theo Tên tắt (tenTat) khi import. Để trống nếu không khớp.
   */
  coach?: (number | null) | Coach;
  lop?: (number | null) | Class;
  /**
   * Mức độ làm bài tập về nhà (số). Giá trị chữ trong file được bỏ qua.
   */
  lamBTVN?: number | null;
  /**
   * Điểm ý thức 1–10. Giá trị ngoài khoảng được bỏ qua khi import.
   */
  yThuc?: number | null;
  kienThucMoi?: string | null;
  nhanXet?: string | null;
  giaoBTVN?: string | null;
  khBuoiSau?: string | null;
  sachDangHoc?: string | null;
  linkLichess?: string | null;
  /**
   * Buổi học tương ứng (suy từ lớp + ngày qua ensureSession). Để trống với bản ghi cũ / không có lớp.
   */
  session?: (number | null) | ClassSession;
  /**
   * Khóa định danh idempotent khi import nhận xét buổi: co_so|buoi|ten_hoc_vien. Để trống với điểm danh nhập tay.
   */
  khoa?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-sessions".
 */
export interface ClassSession {
  id: number;
  /**
   * Buổi gắn lớp (đi-tới). Để trống với buổi lịch sử (theo mã buổi).
   */
  lop?: (number | null) | Class;
  /**
   * Cơ sở của buổi — trục phân quyền. Buổi gắn lớp lấy từ lớp; buổi lịch sử lấy từ HV.
   */
  location?: (number | null) | Location;
  /**
   * Nhãn khối/đợt lịch sử (vd C16, B119). Trống với buổi tạo mới theo lớp.
   */
  buoi?: string | null;
  date: string;
  /**
   * Suy từ ngày khi sinh buổi (snapshot từ lịch tuần).
   */
  thu?: ('t2' | 't3' | 't4' | 't5' | 't6' | 't7' | 'cn') | null;
  gioBatDau?: string | null;
  gioKetThuc?: string | null;
  phong?: string | null;
  /**
   * GV thực tế đứng buổi (dạy thay). Để trống = dùng GV chính của lớp.
   */
  coachThucTe?: (number | null) | Coach;
  troGiangThucTe?: (number | null) | Coach;
  trangThai: 'du_kien' | 'da_day' | 'huy' | 'bu';
  /**
   * Mục tiêu bài học (điền sẵn khi áp khung lộ trình).
   */
  mucTieu?: string | null;
  kienThucMoi?: string | null;
  giaoBTVN?: string | null;
  khBuoiSau?: string | null;
  sachDangHoc?: string | null;
  /**
   * Lý do hủy / ghi chú vận hành.
   */
  ghiChuBuoi?: string | null;
  /**
   * Với buổi dạy bù: trỏ về buổi đã hủy mà nó thay thế.
   */
  buoiGoc?: (number | null) | ClassSession;
  /**
   * Khóa idempotent khi sinh buổi: lop|YYYY-MM-DD. Chống tạo trùng.
   */
  khoaBuoi?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-student-plans".
 */
export interface SessionStudentPlan {
  id: number;
  session: number | ClassSession;
  student: number | Student;
  mucTieu?: string | null;
  sachDangHoc?: string | null;
  kienThucMoi?: string | null;
  giaoBTVN?: string | null;
  khBuoiSau?: string | null;
  /**
   * Khóa idempotent: session|student.
   */
  khoaKeHoach?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curriculum-templates".
 */
export interface CurriculumTemplate {
  id: number;
  tenKhung: string;
  /**
   * Cấp lộ trình khung này phục vụ (Tốt…Vua).
   */
  capDo: 'tot' | 'ma' | 'tuong' | 'xe' | 'hau' | 'vua';
  /**
   * Tùy chọn — tuyến trình độ (Nhập môn / Cơ bản / Nâng cao).
   */
  tuyen?: ('nhap_mon' | 'co_ban' | 'nang_cao') | null;
  moTa?: string | null;
  /**
   * Khung "Lưu trữ" ẩn khỏi danh sách chọn khi áp.
   */
  trangThai?: ('dang_dung' | 'luu_tru') | null;
  /**
   * Thứ tự bài = thứ tự dạy. Bài thứ N điền vào buổi thứ N khi áp.
   */
  baiHoc?:
    | {
        tieuDe?: string | null;
        mucTieu?: string | null;
        kienThucMoi?: string | null;
        giaoBTVN?: string | null;
        sachDangHoc?: string | null;
        /**
         * Ghi chú nội bộ khi soạn — KHÔNG điền vào buổi khi áp.
         */
        ghiChu?: string | null;
        /**
         * Để trống — chỗ neo map nguồn giáo trình (Obsidian/giáo trình Nga) giai đoạn sau.
         */
        nguonRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays".
 */
export interface Holiday {
  id: number;
  /**
   * VD: Tết Nguyên đán, Giỗ tổ Hùng Vương, Nghỉ 30/4–1/5.
   */
  tenNgayNghi: string;
  /**
   * Ngày bắt đầu nghỉ (bao gồm).
   */
  tuNgay: string;
  /**
   * Ngày kết thúc nghỉ (bao gồm). Để trống nếu nghỉ 1 ngày.
   */
  denNgay?: string | null;
  /**
   * Để trống = nghỉ toàn công ty. Chọn 1 hoặc nhiều cơ sở = chỉ các cơ sở đó nghỉ.
   */
  location?: (number | Location)[] | null;
  /**
   * Tắt để tạm ngưng áp dụng ngày nghỉ này khi sinh buổi.
   */
  kichHoat?: boolean | null;
  ghiChu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-reports".
 */
export interface ProgressReport {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  /**
   * Kỳ đánh giá định kỳ (kết hợp học viên thành khóa idempotent).
   */
  period: 'Cuối năm 2024' | '6 tháng đầu 2025' | '6 tháng cuối 2025';
  /**
   * Cấp trên lộ trình @ds/brand tại thời điểm báo cáo.
   */
  level?: ('tot' | 'ma' | 'tuong' | 'xe' | 'hau' | 'vua') | null;
  yThuc?: number | null;
  btvn?: string | null;
  thamGiaGiaiDau?: string | null;
  cacSachDaHoc?: string | null;
  nhanXetChung?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keHoach?: string | null;
  coachComment?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coach?: (number | null) | Coach;
  /**
   * Để trống = nháp (phụ huynh KHÔNG thấy). Điền ngày = phát hành cho phụ huynh.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  /**
   * Chu kỳ/gói buổi mà lần nộp này thuộc về (truy vết Thu ↔ chu kỳ, phục vụ ghi nhận doanh thu & nhắc tái tục). Tùy chọn.
   */
  tuitionCycle?: (number | null) | TuitionCycle;
  ngayNop: string;
  hocPhi?: number | null;
  tienSach?: number | null;
  muaKhac?: number | null;
  hp1Buoi?: number | null;
  soBuoiNop?: number | null;
  coSo?: ('kim_lien' | 'vinh_phuc') | null;
  tinhTrang?: ('da_nop' | 'cho') | null;
  /**
   * Ảnh chụp biên lai/bill (tùy chọn).
   */
  anhBill?: (number | null) | Media;
  ghiChu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-cycles".
 */
export interface TuitionCycle {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  package: '10' | '20' | '40';
  sessionsTotal: number;
  /**
   * Tự động = số buổi điểm danh "Có mặt" của học viên trong [Ngày bắt đầu, Ngày dự kiến hết gói] (không lưu, không nhập tay).
   */
  sessionsUsed?: number | null;
  startDate: string;
  expectedEndDate?: string | null;
  status: 'dang_hoc' | 'sap_het' | 'da_het';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-packages".
 */
export interface TuitionPackage {
  id: number;
  tierName: string;
  sessionCount: number;
  tuition: number;
  benefits?: string | null;
  /**
   * Các lớp áp dụng gói này (để trống = gói chung, không gắn lớp).
   */
  classes?: (number | Class)[] | null;
  /**
   * Học viên được gán gói này (tùy chọn).
   */
  students?: (number | Student)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: number;
  name: string;
  /**
   * Bỏ tick để ẩn danh mục không còn sử dụng (không xóa lịch sử).
   */
  active?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  category: number | ExpenseCategory;
  amount: number;
  spentAt: string;
  coSo?: ('kim_lien' | 'vinh_phuc') | null;
  method?: ('tien_mat' | 'ck') | null;
  payee?: string | null;
  /**
   * Ảnh hóa đơn/biên lai (tùy chọn).
   */
  attachment?: (number | null) | Media;
  note?: string | null;
  trangThai?: ('cho_duyet' | 'da_duyet' | 'tu_choi') | null;
  duyetBoi?: (number | null) | User;
  ngayDuyet?: string | null;
  lyDoTuChoi?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  soTien: number;
  ngayHoan: string;
  lyDo: string;
  coSo?: ('kim_lien' | 'vinh_phuc') | null;
  phuongThuc?: ('tien_mat' | 'ck') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Danh mục sách nội bộ có giá. Khác với "Sách nổi bật" hiển thị trên website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  /**
   * Mã định danh sách (vd TQ1, BTTH1). Khóa chống trùng khi import.
   */
  code: string;
  title: string;
  coverPrice?: number | null;
  salePrice?: number | null;
  levelSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-issues".
 */
export interface BookIssue {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  book?: (number | null) | Book;
  ngayDung?: string | null;
  giaSach?: number | null;
  uuDai?: number | null;
  tienSach?: number | null;
  coSo?: ('kim_lien' | 'vinh_phuc') | null;
  /**
   * Ký hiệu lần phát sách từ Lark — truy vết + chống trùng.
   */
  larkCode?: string | null;
  ghiChu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-books".
 */
export interface FeaturedBook {
  id: number;
  title: string;
  image: number | Media;
  shortDesc?: string | null;
  level?: ('tot' | 'ma' | 'tuong' | 'xe' | 'hau' | 'vua') | null;
  /**
   * Deep-link sang duongsinhbook.com (Sapo).
   */
  sapoUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Đường dẫn URL, ví dụ: khai-giang-lop-ma-thang-3
   */
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  category: 'tin_tuc' | 'kien_thuc_co_vua' | 'su_kien' | 'hoat_dong' | 'khac';
  author?:
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  title: string;
  date: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  type: 'khai_giang' | 'giai_dau' | 'workshop' | 'su_kien_cong_dong' | 'khac';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-locations".
 */
export interface WebLocation {
  id: number;
  /**
   * Vd: "Cơ sở Vĩnh Phúc".
   */
  name: string;
  address: string;
  /**
   * Link Google Maps (mở tab mới khi bấm "Xem bản đồ").
   */
  mapUrl?: string | null;
  /**
   * Vd: "Thứ 2 · Thứ 6" hoặc "Tối Thứ 3 · Thứ 5 · Thứ 7".
   */
  lichHocNgay?: string | null;
  /**
   * Mỗi dòng một ca. Vd: "Ca 1: 18h00–19h15".
   */
  lichHocGio?:
    | {
        gio: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Số nhỏ hơn hiển thị trước.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-coaches".
 */
export interface WebCoach {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  /**
   * Vd: "Huấn luyện viên trưởng", "Huấn luyện viên".
   */
  role?: string | null;
  titles?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Số nhỏ hơn hiển thị trước.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Không còn hiển thị trên website (website nay dùng lớp thật theo 6 cấp). Giữ tạm để tham khảo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-programs".
 */
export interface WebProgram {
  id: number;
  /**
   * Vd: "Nhập môn", "Cơ bản", "Nâng cao".
   */
  name: string;
  shortDesc?: string | null;
  /**
   * Số nhỏ hơn hiển thị trước.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renewal-requests".
 */
export interface RenewalRequest {
  id: number;
  /**
   * Mã định danh nghiệp vụ — tự sinh, bất biến.
   */
  code?: string | null;
  student: number | Student;
  parent: number | Parent;
  tuitionCycle?: (number | null) | TuitionCycle;
  sessionsRemaining: number;
  parentNote?: string | null;
  status: 'moi' | 'dang_xu_ly' | 'da_chot' | 'da_huy';
  staffNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-logs".
 */
export interface ImportLog {
  id: number;
  kind:
    | 'students'
    | 'attendance'
    | 'progress-reports'
    | 'coaches'
    | 'payments'
    | 'classes'
    | 'enrollments'
    | 'session-planning'
    | 'curriculum-apply';
  fileName: string;
  user?: (number | null) | User;
  rowsTotal?: number | null;
  rowsCreated?: number | null;
  rowsUpdated?: number | null;
  rowsSkipped?: number | null;
  rowsErrors?: number | null;
  notes?: string | null;
  /**
   * Một số dòng lỗi đầu tiên để truy vết nhanh.
   */
  errorSample?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete';
  /**
   * Slug collection bị tác động (students, payments, …).
   */
  collectionSlug: string;
  documentId?: string | null;
  /**
   * Chỉ gắn khi chủ thể là nhân viên (Users). Phụ huynh/hệ thống xem cột "Chủ thể".
   */
  user?: (number | null) | User;
  /**
   * Nhãn chủ thể: email nhân viên, parent:<id>, system hoặc unknown.
   */
  actorLabel?: string | null;
  /**
   * create/update: { changes: { field: { from, to } } }. delete: { snapshot: { field } }. Giá trị đã nén (quan hệ→id, richText/chuỗi dài→cắt ngắn).
   */
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-codes".
 */
export interface OtpCode {
  id: number;
  phone: string;
  codeHash: string;
  expiresAt: string;
  consumedAt?: string | null;
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'parents';
        value: number | Parent;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'student-levels';
        value: number | StudentLevel;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'levels';
        value: number | Level;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'attendance';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'class-sessions';
        value: number | ClassSession;
      } | null)
    | ({
        relationTo: 'session-student-plans';
        value: number | SessionStudentPlan;
      } | null)
    | ({
        relationTo: 'curriculum-templates';
        value: number | CurriculumTemplate;
      } | null)
    | ({
        relationTo: 'holidays';
        value: number | Holiday;
      } | null)
    | ({
        relationTo: 'progress-reports';
        value: number | ProgressReport;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'tuition-cycles';
        value: number | TuitionCycle;
      } | null)
    | ({
        relationTo: 'tuition-packages';
        value: number | TuitionPackage;
      } | null)
    | ({
        relationTo: 'expense-categories';
        value: number | ExpenseCategory;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'book-issues';
        value: number | BookIssue;
      } | null)
    | ({
        relationTo: 'featured-books';
        value: number | FeaturedBook;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'web-locations';
        value: number | WebLocation;
      } | null)
    | ({
        relationTo: 'web-coaches';
        value: number | WebCoach;
      } | null)
    | ({
        relationTo: 'web-programs';
        value: number | WebProgram;
      } | null)
    | ({
        relationTo: 'renewal-requests';
        value: number | RenewalRequest;
      } | null)
    | ({
        relationTo: 'import-logs';
        value: number | ImportLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'otp-codes';
        value: number | OtpCode;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'parents';
        value: number | Parent;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'parents';
        value: number | Parent;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  childAge?: T;
  interestedLocation?: T;
  interestedClass?: T;
  source?: T;
  note?: T;
  status?: T;
  assignedTo?: T;
  nextFollowUpAt?: T;
  activityLog?:
    | T
    | {
        type?: T;
        at?: T;
        note?: T;
        by?: T;
        id?: T;
      };
  convertedAt?: T;
  convertedParent?: T;
  convertedStudent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parents_select".
 */
export interface ParentsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  zaloId?: T;
  children?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  code?: T;
  fullName?: T;
  nickname?: T;
  dob?: T;
  capChinh?: T;
  location?: T;
  parents?: T;
  enrollmentStatus?: T;
  note?: T;
  soBuoiTonDauKy?: T;
  ngayChotSoDu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-levels_select".
 */
export interface StudentLevelsSelect<T extends boolean = true> {
  student?: T;
  level?: T;
  trangThai?: T;
  ngayBatDau?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  class?: T;
  ngayBatDau?: T;
  ngayKetThuc?: T;
  dangHoc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "levels_select".
 */
export interface LevelsSelect<T extends boolean = true> {
  tenTat?: T;
  tenDayDu?: T;
  thuTu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  level?: T;
  track?: T;
  ageGroup?: T;
  description?: T;
  location?: T;
  coach?: T;
  troGiang?: T;
  siSoHienTai?: T;
  siSoToiDa?: T;
  trangThai?: T;
  lichHoc?:
    | T
    | {
        thu?: T;
        gioBatDau?: T;
        gioKetThuc?: T;
        phong?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  tenTat?: T;
  tenTatAlias?: T;
  hoTen?: T;
  vaiTro?: T;
  sdt?: T;
  email?: T;
  elo?: T;
  trangThai?: T;
  name?: T;
  photo?: T;
  titles?:
    | T
    | {
        title?: T;
        id?: T;
      };
  bio?: T;
  order?: T;
  luongMoiBuoi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  address?: T;
  lat?: T;
  lng?: T;
  mapEmbedUrl?: T;
  phone?: T;
  isHeadquarters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance_select".
 */
export interface AttendanceSelect<T extends boolean = true> {
  student?: T;
  date?: T;
  status?: T;
  note?: T;
  buoi?: T;
  coach?: T;
  lop?: T;
  lamBTVN?: T;
  yThuc?: T;
  kienThucMoi?: T;
  nhanXet?: T;
  giaoBTVN?: T;
  khBuoiSau?: T;
  sachDangHoc?: T;
  linkLichess?: T;
  session?: T;
  khoa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-sessions_select".
 */
export interface ClassSessionsSelect<T extends boolean = true> {
  lop?: T;
  location?: T;
  buoi?: T;
  date?: T;
  thu?: T;
  gioBatDau?: T;
  gioKetThuc?: T;
  phong?: T;
  coachThucTe?: T;
  troGiangThucTe?: T;
  trangThai?: T;
  mucTieu?: T;
  kienThucMoi?: T;
  giaoBTVN?: T;
  khBuoiSau?: T;
  sachDangHoc?: T;
  ghiChuBuoi?: T;
  buoiGoc?: T;
  khoaBuoi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-student-plans_select".
 */
export interface SessionStudentPlansSelect<T extends boolean = true> {
  session?: T;
  student?: T;
  mucTieu?: T;
  sachDangHoc?: T;
  kienThucMoi?: T;
  giaoBTVN?: T;
  khBuoiSau?: T;
  khoaKeHoach?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curriculum-templates_select".
 */
export interface CurriculumTemplatesSelect<T extends boolean = true> {
  tenKhung?: T;
  capDo?: T;
  tuyen?: T;
  moTa?: T;
  trangThai?: T;
  baiHoc?:
    | T
    | {
        tieuDe?: T;
        mucTieu?: T;
        kienThucMoi?: T;
        giaoBTVN?: T;
        sachDangHoc?: T;
        ghiChu?: T;
        nguonRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays_select".
 */
export interface HolidaysSelect<T extends boolean = true> {
  tenNgayNghi?: T;
  tuNgay?: T;
  denNgay?: T;
  location?: T;
  kichHoat?: T;
  ghiChu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-reports_select".
 */
export interface ProgressReportsSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  period?: T;
  level?: T;
  yThuc?: T;
  btvn?: T;
  thamGiaGiaiDau?: T;
  cacSachDaHoc?: T;
  nhanXetChung?: T;
  keHoach?: T;
  coachComment?: T;
  coach?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  tuitionCycle?: T;
  ngayNop?: T;
  hocPhi?: T;
  tienSach?: T;
  muaKhac?: T;
  hp1Buoi?: T;
  soBuoiNop?: T;
  coSo?: T;
  tinhTrang?: T;
  anhBill?: T;
  ghiChu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-cycles_select".
 */
export interface TuitionCyclesSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  package?: T;
  sessionsTotal?: T;
  sessionsUsed?: T;
  startDate?: T;
  expectedEndDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tuition-packages_select".
 */
export interface TuitionPackagesSelect<T extends boolean = true> {
  tierName?: T;
  sessionCount?: T;
  tuition?: T;
  benefits?: T;
  classes?: T;
  students?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  category?: T;
  amount?: T;
  spentAt?: T;
  coSo?: T;
  method?: T;
  payee?: T;
  attachment?: T;
  note?: T;
  trangThai?: T;
  duyetBoi?: T;
  ngayDuyet?: T;
  lyDoTuChoi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  soTien?: T;
  ngayHoan?: T;
  lyDo?: T;
  coSo?: T;
  phuongThuc?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  coverPrice?: T;
  salePrice?: T;
  levelSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-issues_select".
 */
export interface BookIssuesSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  book?: T;
  ngayDung?: T;
  giaSach?: T;
  uuDai?: T;
  tienSach?: T;
  coSo?: T;
  larkCode?: T;
  ghiChu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-books_select".
 */
export interface FeaturedBooksSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  shortDesc?: T;
  level?: T;
  sapoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  date?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-locations_select".
 */
export interface WebLocationsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  mapUrl?: T;
  lichHocNgay?: T;
  lichHocGio?:
    | T
    | {
        gio?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-coaches_select".
 */
export interface WebCoachesSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  role?: T;
  titles?:
    | T
    | {
        title?: T;
        id?: T;
      };
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-programs_select".
 */
export interface WebProgramsSelect<T extends boolean = true> {
  name?: T;
  shortDesc?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renewal-requests_select".
 */
export interface RenewalRequestsSelect<T extends boolean = true> {
  code?: T;
  student?: T;
  parent?: T;
  tuitionCycle?: T;
  sessionsRemaining?: T;
  parentNote?: T;
  status?: T;
  staffNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-logs_select".
 */
export interface ImportLogsSelect<T extends boolean = true> {
  kind?: T;
  fileName?: T;
  user?: T;
  rowsTotal?: T;
  rowsCreated?: T;
  rowsUpdated?: T;
  rowsSkipped?: T;
  rowsErrors?: T;
  notes?: T;
  errorSample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  user?: T;
  actorLabel?: T;
  diff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-codes_select".
 */
export interface OtpCodesSelect<T extends boolean = true> {
  phone?: T;
  codeHash?: T;
  expiresAt?: T;
  consumedAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}